sonar.projectKey=fullstack-devops-app
sonar.projectName=Fullstack Docker DevOps Project
sonar.sources=frontend,backend
sonar.exclusions=**/node_modules/**, **/.next/**, **/build/**, **/dist/**
sonar.sourceEncoding=UTF-8