sonar.projectKey=fullstack-devops-app
sonar.projectName=Fullstack Docker DevOps Project
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**, **/.next/**, **/build/**, **/dist/**, **/.git/**
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8