sonar.projectKey=fullstack-devops-app
sonar.projectName=Fullstack Docker DevOps Project
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.next/**, **/build/**, **/dist/**, **/.git/**
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.json
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8